-- ============================================
-- SCHEMA PARA SISTEMA DE ÓRDENES Y PAGOS
-- ============================================
-- Sistema completo para manejar checkout multi-tienda
-- con MercadoPago y sincronización a Shopify

-- ============================================
-- PASO 1: CREAR TABLAS
-- ============================================

-- 1. TABLA DE TRANSACCIONES (Pagos de MercadoPago)
CREATE TABLE IF NOT EXISTS transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Identificadores
  mp_payment_id text UNIQUE,              -- ID de pago de MercadoPago
  mp_preference_id text,                  -- ID de preferencia MP

  -- Montos
  total_amount numeric(10, 2) NOT NULL,   -- Monto total pagado
  currency text DEFAULT 'CLP',

  -- Estado
  status text NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'refunded')),
  payment_method text,                     -- credit_card, debit_card, etc.

  -- Información del comprador
  buyer_email text,
  buyer_name text,
  buyer_phone text,

  -- Dirección de envío
  shipping_address jsonb,                  -- { street, number, city, region, zip_code }

  -- Items del carrito (para referencia)
  cart_items jsonb NOT NULL,               -- Array de productos comprados

  -- Distribución por tienda
  store_splits jsonb NOT NULL,             -- { store_domain: amount }

  -- Metadata
  is_test boolean DEFAULT false,           -- Para testing sin cobro real
  metadata jsonb,                          -- Datos adicionales

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone
);

COMMENT ON TABLE transactions IS 'Registro de transacciones de MercadoPago';
COMMENT ON COLUMN transactions.cart_items IS 'Snapshot del carrito al momento de compra';
COMMENT ON COLUMN transactions.store_splits IS 'Distribución de montos por tienda para payout';

-- 2. TABLA DE ÓRDENES SHOPIFY (Una transacción genera múltiples órdenes)
CREATE TABLE IF NOT EXISTS shopify_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Relación con transacción
  transaction_id bigint NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,

  -- Identificadores Shopify
  store_domain text NOT NULL REFERENCES stores(domain) ON DELETE CASCADE,
  shopify_order_id text,                   -- ID de orden en Shopify
  shopify_order_number text,               -- Número de orden visible (#1001)
  shopify_draft_order_id text,             -- Draft order ID (temporal)

  -- Montos de esta orden específica
  order_amount numeric(10, 2) NOT NULL,    -- Monto de esta tienda

  -- Items de esta tienda
  order_items jsonb NOT NULL,              -- Productos de esta tienda solamente

  -- Estado
  status text NOT NULL CHECK (status IN ('draft', 'pending', 'created', 'failed', 'cancelled')),
  fulfillment_status text,                 -- null, fulfilled, partial, etc.

  -- Información adicional
  shopify_order_url text,                  -- URL para ver orden en Shopify Admin
  error_message text,                      -- Si falla la creación

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone       -- Cuando se creó en Shopify
);

COMMENT ON TABLE shopify_orders IS 'Órdenes individuales creadas en cada tienda Shopify';
COMMENT ON COLUMN shopify_orders.order_items IS 'Productos específicos de esta tienda';

-- 3. TABLA DE PAYOUTS (Transferencias a tiendas)
CREATE TABLE IF NOT EXISTS payouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Relación con tienda
  store_domain text NOT NULL REFERENCES stores(domain) ON DELETE CASCADE,

  -- Monto
  amount numeric(10, 2) NOT NULL,
  currency text DEFAULT 'CLP',

  -- Transferencia
  transfer_method text CHECK (transfer_method IN ('manual', 'mercadopago', 'bank_transfer')),
  transfer_id text,                        -- ID de transferencia en MP o banco
  transfer_reference text,                 -- Referencia bancaria

  -- Estado
  status text NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed')),

  -- Período cubierto
  period_start date,
  period_end date,

  -- Órdenes incluidas en este payout
  included_orders bigint[],                -- Array de shopify_orders.id

  -- Metadata
  notes text,
  metadata jsonb,

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone
);

COMMENT ON TABLE payouts IS 'Registro de transferencias de fondos a tiendas';
COMMENT ON COLUMN payouts.included_orders IS 'IDs de órdenes incluidas en este pago';

-- 4. TABLA DE USUARIOS (para futuro)
CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Identificación
  email text UNIQUE NOT NULL,
  phone text,
  full_name text,

  -- Direcciones guardadas
  saved_addresses jsonb[],

  -- Preferencias
  preferences jsonb,

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone
);

COMMENT ON TABLE users IS 'Usuarios de la app (futuro sistema de cuentas)';

-- ============================================
-- PASO 2: ÍNDICES
-- ============================================

-- Transactions
CREATE INDEX IF NOT EXISTS idx_transactions_mp_payment ON transactions(mp_payment_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_email ON transactions(buyer_email);
CREATE INDEX IF NOT EXISTS idx_transactions_created ON transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_is_test ON transactions(is_test);

-- Shopify Orders
CREATE INDEX IF NOT EXISTS idx_shopify_orders_transaction ON shopify_orders(transaction_id);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_store ON shopify_orders(store_domain);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_shopify_id ON shopify_orders(shopify_order_id);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_status ON shopify_orders(status);
CREATE INDEX IF NOT EXISTS idx_shopify_orders_created ON shopify_orders(created_at DESC);

-- Payouts
CREATE INDEX IF NOT EXISTS idx_payouts_store ON payouts(store_domain);
CREATE INDEX IF NOT EXISTS idx_payouts_status ON payouts(status);
CREATE INDEX IF NOT EXISTS idx_payouts_period ON payouts(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_payouts_created ON payouts(created_at DESC);

-- Users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ============================================
-- PASO 3: ROW LEVEL SECURITY
-- ============================================

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopify_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura (desarrollo)
CREATE POLICY "transactions_select_policy" ON transactions
  FOR SELECT USING (true);

CREATE POLICY "shopify_orders_select_policy" ON shopify_orders
  FOR SELECT USING (true);

CREATE POLICY "payouts_select_policy" ON payouts
  FOR SELECT USING (true);

CREATE POLICY "users_select_policy" ON users
  FOR SELECT USING (true);

-- Políticas de escritura (desarrollo)
CREATE POLICY "transactions_insert_policy" ON transactions
  FOR INSERT WITH CHECK (true);

CREATE POLICY "transactions_update_policy" ON transactions
  FOR UPDATE USING (true);

CREATE POLICY "shopify_orders_insert_policy" ON shopify_orders
  FOR INSERT WITH CHECK (true);

CREATE POLICY "shopify_orders_update_policy" ON shopify_orders
  FOR UPDATE USING (true);

CREATE POLICY "payouts_insert_policy" ON payouts
  FOR INSERT WITH CHECK (true);

CREATE POLICY "payouts_update_policy" ON payouts
  FOR UPDATE USING (true);

CREATE POLICY "users_insert_policy" ON users
  FOR INSERT WITH CHECK (true);

CREATE POLICY "users_update_policy" ON users
  FOR UPDATE USING (true);

-- ============================================
-- PASO 4: FUNCIONES ÚTILES
-- ============================================

-- Función para auto-actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para updated_at
CREATE TRIGGER transactions_updated_at_trigger
  BEFORE UPDATE ON transactions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER shopify_orders_updated_at_trigger
  BEFORE UPDATE ON shopify_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER payouts_updated_at_trigger
  BEFORE UPDATE ON payouts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER users_updated_at_trigger
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Función para calcular balance pendiente de una tienda
CREATE OR REPLACE FUNCTION get_store_pending_balance(store_domain_param text)
RETURNS numeric AS $$
DECLARE
  total_sales numeric;
  total_paid numeric;
BEGIN
  -- Sumar todas las órdenes aprobadas de la tienda
  SELECT COALESCE(SUM(order_amount), 0)
  INTO total_sales
  FROM shopify_orders so
  JOIN transactions t ON so.transaction_id = t.id
  WHERE so.store_domain = store_domain_param
    AND so.status = 'created'
    AND t.status = 'approved';

  -- Restar lo ya pagado
  SELECT COALESCE(SUM(amount), 0)
  INTO total_paid
  FROM payouts
  WHERE store_domain = store_domain_param
    AND status = 'completed';

  RETURN total_sales - total_paid;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_store_pending_balance IS 'Calcula balance pendiente de pago a una tienda';

-- Función para obtener órdenes de un usuario
CREATE OR REPLACE FUNCTION get_user_orders(email_param text)
RETURNS TABLE (
  transaction_id bigint,
  total_amount numeric,
  status text,
  created_at timestamp with time zone,
  items_count integer,
  stores_count integer
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    t.id as transaction_id,
    t.total_amount,
    t.status,
    t.created_at,
    jsonb_array_length(t.cart_items) as items_count,
    jsonb_object_length(t.store_splits) as stores_count
  FROM transactions t
  WHERE t.buyer_email = email_param
  ORDER BY t.created_at DESC;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_user_orders IS 'Obtiene todas las órdenes de un usuario por email';

-- ============================================
-- PASO 5: VISTAS ÚTILES
-- ============================================

-- Vista de resumen de ventas por tienda
CREATE OR REPLACE VIEW store_sales_summary AS
SELECT
  so.store_domain,
  s.store_name,
  COUNT(DISTINCT so.id) as total_orders,
  SUM(so.order_amount) as total_sales,
  COUNT(DISTINCT CASE WHEN t.status = 'approved' THEN so.id END) as approved_orders,
  SUM(CASE WHEN t.status = 'approved' THEN so.order_amount ELSE 0 END) as approved_sales,
  MIN(so.created_at) as first_order_date,
  MAX(so.created_at) as last_order_date
FROM shopify_orders so
JOIN transactions t ON so.transaction_id = t.id
LEFT JOIN stores s ON so.store_domain = s.domain
GROUP BY so.store_domain, s.store_name;

COMMENT ON VIEW store_sales_summary IS 'Resumen de ventas por tienda';

-- ============================================
-- VERIFICACIÓN FINAL
-- ============================================

DO $$
DECLARE
  transactions_count integer;
  orders_count integer;
  payouts_count integer;
  users_count integer;
BEGIN
  SELECT COUNT(*) INTO transactions_count FROM information_schema.columns WHERE table_name = 'transactions';
  SELECT COUNT(*) INTO orders_count FROM information_schema.columns WHERE table_name = 'shopify_orders';
  SELECT COUNT(*) INTO payouts_count FROM information_schema.columns WHERE table_name = 'payouts';
  SELECT COUNT(*) INTO users_count FROM information_schema.columns WHERE table_name = 'users';

  RAISE NOTICE '';
  RAISE NOTICE '╔════════════════════════════════════════════════╗';
  RAISE NOTICE '║  ✅ SCHEMA DE ÓRDENES CREADO CORRECTAMENTE    ║';
  RAISE NOTICE '╚════════════════════════════════════════════════╝';
  RAISE NOTICE '';
  RAISE NOTICE '📊 Resumen:';
  RAISE NOTICE '   • Tabla transactions: % columnas', transactions_count;
  RAISE NOTICE '   • Tabla shopify_orders: % columnas', orders_count;
  RAISE NOTICE '   • Tabla payouts: % columnas', payouts_count;
  RAISE NOTICE '   • Tabla users: % columnas', users_count;
  RAISE NOTICE '';
  RAISE NOTICE '🚀 Sistema de órdenes listo para usar';
  RAISE NOTICE '';
END $$;
