-- ============================================
-- SCHEMA PROFESIONAL PARA PRODUCTOS EN CACHE
-- ============================================
-- Ejecutar en Supabase SQL Editor

-- 1. TABLA DE PRODUCTOS (Cache de Shopify)
CREATE TABLE IF NOT EXISTS products (
  id text PRIMARY KEY,                    -- Shopify product ID
  store_domain text NOT NULL,             -- FK to stores.domain
  title text NOT NULL,
  description text,
  price numeric(10, 2) NOT NULL,
  compare_at_price numeric(10, 2),        -- Precio anterior (para descuentos)
  vendor text,                             -- Marca/Fabricante
  product_type text,                       -- Categoría/Tipo
  tags text[],                             -- Array de tags para filtros
  images text[],                           -- Array de URLs de imágenes
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone DEFAULT now(), -- Última sincronización
  available boolean DEFAULT true,

  -- Índices para búsquedas rápidas
  CONSTRAINT fk_store FOREIGN KEY (store_domain) REFERENCES stores(domain) ON DELETE CASCADE
);

-- 2. TABLA DE VARIANTES (Tallas, colores, etc.)
CREATE TABLE IF NOT EXISTS product_variants (
  id text PRIMARY KEY,                    -- Shopify variant ID
  product_id text NOT NULL,               -- FK to products.id
  title text NOT NULL,                    -- "Small", "Red", etc.
  price numeric(10, 2) NOT NULL,
  compare_at_price numeric(10, 2),
  sku text,                                -- SKU del inventario
  barcode text,
  inventory_quantity integer DEFAULT 0,
  available boolean DEFAULT true,
  weight numeric(10, 2),
  weight_unit text,
  created_at timestamp with time zone DEFAULT now(),

  CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- 3. TABLA DE SINCRONIZACIÓN (Log de syncs)
CREATE TABLE IF NOT EXISTS sync_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_domain text NOT NULL,
  status text NOT NULL,                   -- 'success', 'error', 'in_progress'
  products_synced integer DEFAULT 0,
  products_added integer DEFAULT 0,
  products_updated integer DEFAULT 0,
  products_deleted integer DEFAULT 0,
  error_message text,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  duration_seconds integer,

  CONSTRAINT fk_store_sync FOREIGN KEY (store_domain) REFERENCES stores(domain) ON DELETE CASCADE
);

-- ============================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================

-- Búsqueda por tienda (muy común)
CREATE INDEX IF NOT EXISTS idx_products_store_domain ON products(store_domain);

-- Búsqueda por tipo de producto
CREATE INDEX IF NOT EXISTS idx_products_type ON products(product_type);

-- Búsqueda por precio (para filtros)
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);

-- Búsqueda por disponibilidad
CREATE INDEX IF NOT EXISTS idx_products_available ON products(available) WHERE available = true;

-- Full-text search en título y descripción
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING gin(to_tsvector('spanish', title || ' ' || COALESCE(description, '')));

-- Tags search
CREATE INDEX IF NOT EXISTS idx_products_tags ON products USING gin(tags);

-- Variantes por producto
CREATE INDEX IF NOT EXISTS idx_variants_product ON product_variants(product_id);

-- Logs por tienda
CREATE INDEX IF NOT EXISTS idx_sync_logs_store ON sync_logs(store_domain);
CREATE INDEX IF NOT EXISTS idx_sync_logs_started ON sync_logs(started_at DESC);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;

-- Políticas: Todos pueden leer (público)
CREATE POLICY "Products are viewable by everyone"
  ON products FOR SELECT
  USING (true);

CREATE POLICY "Variants are viewable by everyone"
  ON product_variants FOR SELECT
  USING (true);

-- Logs solo visibles para admins (por ahora público para desarrollo)
CREATE POLICY "Sync logs are viewable by everyone"
  ON sync_logs FOR SELECT
  USING (true);

-- Solo backend puede escribir (o admins autenticados en producción)
CREATE POLICY "Allow insert products"
  ON products FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow update products"
  ON products FOR UPDATE
  USING (true);

CREATE POLICY "Allow delete products"
  ON products FOR DELETE
  USING (true);

CREATE POLICY "Allow insert variants"
  ON product_variants FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow update variants"
  ON product_variants FOR UPDATE
  USING (true);

CREATE POLICY "Allow delete variants"
  ON product_variants FOR DELETE
  USING (true);

CREATE POLICY "Allow insert sync logs"
  ON sync_logs FOR INSERT
  WITH CHECK (true);

-- ============================================
-- FUNCIONES ÚTILES
-- ============================================

-- Función para actualizar el timestamp updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para products
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- FUNCIÓN DE BÚSQUEDA (Full-text)
-- ============================================

CREATE OR REPLACE FUNCTION search_products(
  search_query text,
  store_filter text DEFAULT NULL,
  limit_count integer DEFAULT 50
)
RETURNS TABLE (
  id text,
  store_domain text,
  title text,
  description text,
  price numeric,
  images text[],
  rank real
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.store_domain,
    p.title,
    p.description,
    p.price,
    p.images,
    ts_rank(to_tsvector('spanish', p.title || ' ' || COALESCE(p.description, '')), plainto_tsquery('spanish', search_query)) as rank
  FROM products p
  WHERE
    to_tsvector('spanish', p.title || ' ' || COALESCE(p.description, '')) @@ plainto_tsquery('spanish', search_query)
    AND (store_filter IS NULL OR p.store_domain = store_filter)
    AND p.available = true
  ORDER BY rank DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- VERIFICACIÓN
-- ============================================

-- Ver todas las tablas creadas
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_name IN ('products', 'product_variants', 'sync_logs')
ORDER BY table_name, ordinal_position;

-- Ver índices creados
SELECT indexname, tablename
FROM pg_indexes
WHERE tablename IN ('products', 'product_variants', 'sync_logs');

SELECT 'Schema creado correctamente!' as status;
