-- Run this in your Supabase SQL Editor to create the necessary table

create table if not exists stores (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  access_token text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Enable Row Level Security (RLS)
alter table stores enable row level security;

-- Policy to allow anyone to read stores (since it's a public marketplace)
create policy "Public stores are viewable by everyone"
  on stores for select
  using ( true );

-- Policy to allow inserting new stores (for demo purposes, allowing public insert)
-- In a real app, you would restrict this to authenticated admins
create policy "Anyone can register a store"
  on stores for insert
  with check ( true );

create policy "Anyone can delete a store"
  on stores for delete
  using ( true );

